In [2]:
import numpy as np
import pandas as pd

In [3]:
dataset = pd.read_csv(r'mobile_price.csv')
dataset

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [4]:
df = dataset
df

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [6]:
x = df[['battery_power', 'four_g', 'int_memory', 'ram']]
x

battery_power  four_g  int_memory   ram
0               842       0           7  2549
1              1021       1          53  2631
2               563       1          41  2603
3               615       0          10  2769
4              1821       1          44  1411
...             ...     ...         ...   ...
1995            794       1           2   668
1996           1965       0          39  2032
1997           1911       1          36  3057
1998           1512       1          46   869
1999            510       1          45  3919

[2000 rows x 4 columns]

In [7]:
y = df['price_range']
y

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

In [8]:
#Import statement "from sklearn.model_selection import train_test_split" digunakan untuk mengimpor fungsi train_test_split dari modul model_selection dalam pustaka scikit-learn (sklearn).
from sklearn.model_selection import train_test_split

In [9]:

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 10)

In [10]:
#Melakukan penskalaan fitur menggunakan StandardScaler dari pustaka scikit-learn (sklearn) dalam persiapan data sebelum melatih dan menguji model.
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)


In [11]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)

In [12]:
knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [13]:
x_test

array([[ 1.50714613,  0.95238237, -0.7697728 ,  0.7021008 ],
       [ 1.29479123, -1.04999844, -0.87995677,  0.74824091],
       [-1.45668901, -1.04999844,  0.99317081,  0.07274969],
       ...,
       [ 1.27652414,  0.95238237, -0.10866895, -1.53661737],
       [ 0.48647255,  0.95238237,  1.10335478,  0.2425453 ],
       [-0.94292714,  0.95238237,  0.16679099,  0.23700848]])

In [14]:
y_pred = knn.predict(x_test)
y_pred

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\base.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  old_joblib = LooseVersion(joblib_version) < LooseVersion('0.12')
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\base.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  old_joblib = LooseVersion(joblib_version) < LooseVersion('0.12')


array([3, 3, 1, 3, 1, 3, 3, 2, 1, 3, 2, 3, 0, 1, 0, 3, 1, 3, 2, 3, 3, 3,
       0, 1, 0, 0, 2, 3, 1, 1, 2, 0, 3, 3, 2, 2, 1, 1, 3, 0, 3, 2, 2, 0,
       0, 3, 2, 0, 2, 2, 1, 3, 2, 3, 3, 3, 2, 3, 1, 0, 1, 1, 0, 0, 3, 0,
       1, 0, 1, 3, 2, 2, 0, 1, 3, 2, 3, 3, 2, 1, 2, 0, 1, 0, 1, 3, 1, 3,
       3, 3, 2, 3, 3, 3, 3, 2, 0, 1, 1, 1, 3, 0, 1, 2, 2, 3, 2, 1, 2, 2,
       2, 0, 3, 1, 1, 1, 1, 1, 3, 0, 1, 1, 3, 2, 1, 3, 0, 3, 2, 0, 3, 3,
       3, 1, 2, 0, 0, 2, 3, 1, 3, 0, 3, 3, 0, 3, 2, 1, 2, 0, 1, 0, 0, 2,
       0, 1, 0, 0, 2, 0, 1, 1, 3, 3, 2, 2, 0, 1, 1, 1, 3, 3, 3, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 3, 3, 0, 1, 3, 0, 3, 1, 1, 1, 3, 2, 0, 0, 0,
       0, 3, 1, 3, 3, 3, 1, 1, 2, 1, 2, 0, 2, 1, 1, 3, 3, 1, 3, 2, 2, 1,
       3, 2, 0, 3, 0, 0, 1, 2, 0, 1, 1, 1, 0, 3, 0, 1, 0, 2, 0, 3, 0, 2,
       1, 1, 1, 3, 2, 3, 0, 3, 1, 1, 0, 3, 2, 1, 2, 1, 1, 3, 2, 1, 1, 1,
       3, 2, 3, 0, 2, 2, 2, 2, 0, 3, 0, 2, 1, 1, 2, 0, 3, 3, 0, 1, 1, 1,
       3, 0, 0, 1, 1, 0, 2, 3, 2, 1, 2, 0, 0, 3, 1,

In [20]:
knn.predict_proba(x_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\base.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  old_joblib = LooseVersion(joblib_version) < LooseVersion('0.12')
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\base.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  old_joblib = LooseVersion(joblib_version) < LooseVersion('0.12')


array([[0. , 0. , 0.2, 0.8],
       [0. , 0. , 0.2, 0.8],
       [0. , 0.6, 0.4, 0. ],
       ...,
       [1. , 0. , 0. , 0. ],
       [0. , 0.4, 0.6, 0. ],
       [0. , 0.6, 0.4, 0. ]])

In [21]:
from sklearn.metrics import classification_report, confusion_matrix

In [22]:
print(confusion_matrix(y_test, y_pred))

[[83  9  0  0]
 [12 74 11  0]
 [ 0 23 73 13]
 [ 0  0 11 91]]


In [23]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
y_pred = knn.predict(x_test)
print(classification_report(y_test, y_pred))
print("Accuracy:",accuracy_score(y_pred, y_test)*100,"%")

              precision    recall  f1-score   support

           0       0.87      0.90      0.89        92
           1       0.70      0.76      0.73        97
           2       0.77      0.67      0.72       109
           3       0.88      0.89      0.88       102

    accuracy                           0.80       400
   macro avg       0.80      0.81      0.80       400
weighted avg       0.80      0.80      0.80       400

Accuracy: 80.25 %


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\base.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  old_joblib = LooseVersion(joblib_version) < LooseVersion('0.12')
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\base.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  old_joblib = LooseVersion(joblib_version) < LooseVersion('0.12')
